test/battle_solutions/check_brackets_test.clj
test/battle_solutions/check_parentheses_test.clj

* Add assert require into check_brackets.clj
* Format check_parentheses.clj

Fix bugs in check brackets issue

---

source/find_missing_number.yml
test/battle_solutions/find_missing_number_test.clj

В последовательности записаны целые числа от 1 до N в произвольном порядке, но одно из чисел пропущено (остальные встречаются ровно по одному разу). N заранее неизвестно. Определить пропущенное число

Add find missing number issue

---

test/battle_solutions/move_zeros_test.clj
test/battle_solutions/string_made_of_test.clj

Мб. включить `cljfmt check` в тестовый сценарий на CI?

Refactoring. Fix code style

---

README.md
project.clj
src/battle_asserts/issues/fibonacci.clj
src/battle_asserts/issues/isomorphic_strings.clj
src/battle_asserts/issues/pascals_triangle.clj
src/battle_asserts/issues/separate_with_comma.clj
src/battle_asserts/issues/squish.clj
src/battle_asserts/issues/string_made_of.clj
src/battle_asserts/issues/sum_of_array_plus_one.clj
src/battle_asserts/issues/sum_primes.clj
src/battle_asserts/issues/the_big_divide.clj
src/battle_asserts/issues/twenty_one.clj
src/battle_asserts/issues/underscore.clj
src/battle_asserts/issues/word_positions.clj

- Readme and project file texts
- Asserts small fixes + translations

Readme and descriptions fixes

---

src/battle_asserts/issues/distance_across_river.clj
test/battle_asserts/issues/distance_across_river_test.clj

Develop a function that computes the distance a boat travels across a river, given the width of the river, the boat's speed perpendicular to the river, and the river's speed. Speed is distance/time, and the Pythagorean theorem is c2 = a2 + b2.

Add river distance problem

---

src/battle_asserts/issues/rect_area.clj
test/battle_asserts/issues/rect_area_test.clj

Write the contract, purpose, and header for a function that computes the area of a rectangle given its length and width.

Add rect area problem

---

src/battle_asserts/issues/credit_card_validator.clj

* Fix description
* Improve solution

Fix credit card validation issue

---

src/battle_asserts/issues/drop_every_n_element.clj
src/battle_asserts/issues/missing_number_in_progression.clj

Fix some argument generators

---

src/battle_asserts/issues/distance_across_river.clj

Немного улучшил код генератора, без изменения логики.

Refactoring argument generator for distance river

---

src/battle_asserts/core.clj

Replace doall to doseq

---

src/battle_asserts/core.clj
src/battle_asserts/issues/stairway_to_heaven.clj

Close #373
- Add stairway to heaven task
- Add ability to use samples as asserts

add optional solutions

---

src/battle_asserts/issues/guess_score.clj
test/battle_asserts/issues/guess_score_test.clj

Added guess score

---

src/battle_asserts/issues/function_max.clj
test/battle_asserts/issues/function_max_test.clj

Add function max task

---

src/battle_asserts/issues/biggest_square_sum.clj
test/battle_asserts/issues/biggest_square_sum_test.clj

Biggest square sum issue

---

src/battle_asserts/issues/invert_case.clj
test/battle_asserts/issues/invert_case_test.clj

Add invert-case task

---

src/battle_asserts/issues/circle_point.clj
test/battle_asserts/issues/circle_point_test.clj

Add circle point task

---

src/battle_asserts/issues/complex_number_sum.clj
test/battle_asserts/issues/complex_number_sum_test.clj

Add complex number sum task

---

src/battle_asserts/issues/complex_number_mul.clj
test/battle_asserts/issues/complex_number_mul_test.clj

Complex number mul

---

src/battle_asserts/issues/even_array_square_sum.clj
test/battle_asserts/issues/even_array_square_sum_test.clj

Add even array square sum task

---

src/battle_asserts/issues/straight_line_equation.clj
test/battle_asserts/issues/straight_line_equation_test.clj

Add straight line equation task

---

src/battle_asserts/issues/circle_point.clj
test/battle_asserts/issues/circle_point_test.clj

https://hexlet-ru.slack.com/files/U0XGU0KPV/F016TAAG3DL/image.png

Circle point issue

---

src/battle_asserts/issues/max_abs_elem.clj
test/battle_asserts/issues/max_abs_elem_test.clj

Add max abs element task

---

src/battle_asserts/issues/complex_number_div.clj
test/battle_asserts/issues/complex_number_div_test.clj

Add complex number division task

---

src/battle_asserts/issues/word_match.clj
test/battle_asserts/issues/word_match_test.clj

Add word match task

---

src/battle_asserts/issues/grade_calculator.clj
test/battle_asserts/issues/grade_calculator_test.clj

Grade calc

---

src/battle_asserts/issues/numeric_string_to_array.clj
test/battle_asserts/issues/numeric_string_to_array_test.clj

Numeric string to arr

---

src/battle_asserts/issues/smallest_second_number.clj
test/battle_asserts/issues/smallest_second_number_test.clj

Add solution for smallest second number issue

---

src/battle_asserts/issues/celsius_to_fahrenheit.clj
test/battle_asserts/issues/celsius_to_fahrenheit_test.clj

Add solution for celsius to fahrenheit issue

---

src/battle_asserts/issues/biggest_second_number.clj
test/battle_asserts/issues/biggest_second_number_test.clj

Add solution for biggest second number issue

---

src/battle_asserts/issues/least_common_multiple.clj
test/battle_asserts/issues/least_common_multiple_test.clj

Add solution for least common multiple issue

---

src/battle_asserts/issues/cube_sum.clj
test/battle_asserts/issues/cube_sum_test.clj

Add solution for cube sum issue

---

src/battle_asserts/issues/triangle_area.clj
test/battle_asserts/issues/triangle_area_test.clj

Triangle area

---

src/battle_asserts/issues/complex_number_mul.clj
test/battle_asserts/issues/complex_number_mul_test.clj

Increase difficulty and fix signature for complex number multiplication task

---

src/battle_asserts/issues/complex_number_sum.clj
test/battle_asserts/issues/complex_number_sum_test.clj

Increase difficulty and fix signature for complex number addition task

---

src/battle_asserts/issues/complex_number_sub.clj

Increase difficulty and fix signature for complex number substraction task

---

src/battle_asserts/issues/complex_number_div.clj

Increase difficulty and fix signature for complex number div task

---

src/battle_asserts/issues/operation_suggestion.clj
test/battle_asserts/issues/operation_suggestion_test.clj

Add solution for operation suggestion issue

---

src/battle_asserts/issues/prime_array.clj
test/battle_asserts/issues/prime_array_test.clj

Add solution for prime array issue

---

src/battle_asserts/issues/string_only_digits.clj
test/battle_asserts/issues/string_only_digits_test.clj

Add solution for only digits string issue

---

src/battle_asserts/issues/string_index_of.clj
test/battle_asserts/issues/string_index_of_test.clj

Add solution for string index of issue

---

src/battle_asserts/issues/straight_line_equation.clj
test/battle_asserts/issues/straight_line_equation_test.clj

Straight line equation

---

src/battle_asserts/issues/luke_relations.clj
test/battle_asserts/issues/luke_relations_test.clj

Add solution for luke relations issue

---

src/battle_asserts/issues/double_base_palindromes.clj

Speed up double base palindrome test

---

src/battle_asserts/issues/four_is_magic.clj
test/battle_asserts/issues/four_is_magic_test.clj

Add solution for four is magic task

---

src/battle_asserts/issues/complex_number_sub.clj
test/battle_asserts/issues/complex_number_sub_test.clj

Complex number sub

---

src/battle_asserts/issues/complex_number_sum.clj
test/battle_asserts/issues/complex_number_sum_test.clj

Complex number sum

---

src/battle_asserts/issues/travelling_salesman_problem.clj
test/battle_asserts/issues/travelling_salesman_problem_test.clj

Add solution for travelling salesman problem task

---

src/battle_asserts/issues/get_file.clj
test/battle_asserts/issues/get_file_test.clj

Add solution for get file task

---

src/battle_asserts/issues/passengers_and_driver.clj
test/battle_asserts/issues/passengers_and_driver_test.clj

Add solution for passengers and driver task

---

src/battle_asserts/issues/sastry_numbers.clj
test/battle_asserts/issues/sastry_numbers_test.clj

Add solution for sastry numbers task

---

src/battle_asserts/issues/equality_count.clj
test/battle_asserts/issues/equality_count_test.clj

Add solution for equality count task

---

src/battle_asserts/issues/same_bread.clj
test/battle_asserts/issues/same_bread_test.clj

Add solution for same bread task

---

src/battle_asserts/issues/additive_inverse.clj
test/battle_asserts/issues/additive_inverse_test.clj

Add solution for additive inverse task

---

src/battle_asserts/issues/stickers_count.clj
test/battle_asserts/issues/stickers_count_test.clj

Add solution for stickers count task

---

src/battle_asserts/issues/star_number.clj
test/battle_asserts/issues/star_number_test.clj

Add solution for star number task

---

src/battle_asserts/issues/missing_third_angle.clj
test/battle_asserts/issues/missing_third_angle_test.clj

Add solution for missing third angle task

---

src/battle_asserts/issues/plural_or_singular.clj
test/battle_asserts/issues/plural_or_singular_test.clj

Add solution for plural or singular word task

---

src/battle_asserts/issues/anagram_finder.clj
test/battle_asserts/issues/anagram_finder_test.clj

Add spec tests for anagram-finder

---

src/battle_asserts/issues/sam_with_frodo.clj
test/battle_asserts/issues/sam_with_frodo_test.clj

Add solution for sam with frodo issue

---

src/battle_asserts/issues/card_number_hiding.clj
test/battle_asserts/issues/card_number_hiding_test.clj

Add solution for card number hiding issue

---

src/battle_asserts/issues/secret_society.clj
test/battle_asserts/issues/secret_society_test.clj

Add solution for secret society issue

---

src/battle_asserts/issues/squares_and_cubes.clj
test/battle_asserts/issues/squares_and_cubes_test.clj

Add solution for squares and cubes issue

---

src/battle_asserts/issues/pie_slice.clj
test/battle_asserts/issues/pie_slice_test.clj

Pie slice issue

---

src/battle_asserts/issues/fps_calculation.clj
test/battle_asserts/issues/fps_calculation_test.clj

Add solution for fps calculation issue

---

src/battle_asserts/issues/farm_problem.clj
test/battle_asserts/issues/farm_problem_test.clj

Add solution for farm problem issue

---

src/battle_asserts/issues/plural_or_singular.clj
test/battle_asserts/issues/plural_or_singular_test.clj

Plural or singular fix

---

src/battle_asserts/issues/biggest_second_number.clj
src/battle_asserts/issues/smallest_second_number.clj

Fix signatures

---

src/battle_asserts/issues/tic_tac_toe.clj

feature add tic_tac_toe exercise

---

src/battle_asserts/issues/desc_order.clj

Feature: add desc_order exercise

---

src/battle_asserts/issues/sort_by_length.clj

Current description allows following solution, but tests fail.
```python
def solution(words: List[str]) -> List[str]:
return list(reversed(sorted(words, key=len)))
```

Add important point to description

---

src/battle_asserts/issues/leap_year.clj

This description give more clear definition of leap year.

Maybe change description?

---

src/battle_asserts/issues/reverse_everywhere.clj

Add reverse everywhere task

---

test/test_helper.clj

Refactor typing in tests

---

src/battle_asserts/utility.clj
test/battle_asserts/helper_test.clj
test/test_helper.clj

Add tests for helper and replace tests in generator

---

src/battle_asserts/issues/broadcast_finder.clj

Refactor broadcast finder

---

README.md
test/battle_asserts/core_test.clj
test/test_helper.clj

Task level check tests

---

test/test_helper.clj

Simplify test helper

---

test/battle_asserts/helper_test.clj
test/test_helper.clj

Add nested hashes typing

---

src/battle_asserts/issues/garden_help.clj

Add garden help task

---

src/battle_asserts/issues/rock_scissors_paper.clj

after a long, long way, finally, wrote my first task

add rock_scissors_paper issue

---

src/battle_asserts/issues/reverse_with_capitalize.clj

Add reverse with capitalize task

---

src/battle_asserts/issues/xor.clj

There is some problem for solving this task on Python

Disable xor task

---

src/battle_asserts/issues/moving_sum.clj

хотел сначала сделать задачку про старое доброе среднее скользящее, написал, и понял, что это опять про деление, и у всех будут разной точности результаты)
пришлось упростить до сумм

add moving_sum task

---

src/battle_asserts/issues/reverse_with_capitalize.clj

Change difficulty

---

src/battle_asserts/issues/computers_count.clj

Computers count task

---

src/battle_asserts/issues/tournament_rounds.clj

В текущей версии задания не очень понятно что имеется в виду под раундами, какая зависимость от каких параметров. Новое описание даёт больше полезной информации.

Новое описание задачи на расчёт количества раундов

---

src/battle_asserts/issues/dir_count.clj

Fix description for dir_count task

---

.github/workflows/build.yml
.github/workflows/release.yml

- Fix release issues on GH Actions
- Fix release tag and name

fix release

---

README.md

Добавил стандартную для всех наших реп подпись

add info about hexlet

---

.github/workflows/build.yml
.github/workflows/release.yml
deps.edn
src/battle_asserts/issues/students_discipline_count.clj
src/battle_asserts/utility_tools.clj

Small improvements

---

.gitignore
CONTRIBUTING.md
Makefile
README.md
deps.edn
src/battle_asserts/utility_tools.clj

- Add issue generator tool
- Update info
- Add issue generator to commands
- Update .gitignore

Create issue template generator

---

deps.edn
src/battle_asserts/issues/leaders_in_an_array.clj
src/battle_asserts/issues/numeric_string_to_array.clj
src/battle_asserts/utility_tools.clj

- Update generator tool
- Update command
- Remove obsolete
- Replace `vec` to `mapv`

Improve issue template generator

---

Makefile
src/battle_asserts/issues/split_names.clj
src/battle_asserts/utility_tools.clj
tests.edn

- Remove obsolete command
- Fix template
- Add profiling to tests
- Add split names task

Add new task and do small improvements

---

deps.edn

- Bump formatter
- Reformat deps

Bump formatter

---

src/battle_asserts/issues/function_max.clj

Примените эту функкцию к целочисленному массиву и найдите наибольшее число.

remove double 'к'

---

src/battle_asserts/issues/minmax_find.clj

Clarify task description

---

src/battle_asserts/issues/first_repeating_element.clj

add letter 'в' in word 'первый'

---

src/battle_asserts/issues/pythagorean_triple.clj

Issue: https://github.com/hexlet-codebattle/battle_asserts/issues/975

Fix pythagorean_triple example

---

src/battle_asserts/core.clj

Fixes #873﻿
Merge when codebattle backend is ready

#873 Rework assertions json format

---

src/battle_asserts/issues/largest_swap.clj

Fix largest swap

---

src/battle_asserts/issues/supremum_syracuse.clj

Fixup supremum-syracuse soluiton

---

src/battle_asserts/issues/circle_point.clj

Для задачи circle_point добавил подсказку из англоязычного описания в описание на русском языке.

add tip to russian description of circle_point task

---

src/battle_asserts/issues/how_heavy.clj

Добавил перевод слов radius и height. Исправил несогласованные слова.

modify russian description of how_heavy task

---

src/battle_asserts/issues/number_range.clj

There are no tests to check the number inclusive lower & upper

Add more tests

---

src/battle_asserts/issues/ruth_aaron_pairs.clj

Fix ruth aaron pairs issue

---

src/battle_asserts/issues/garland_word.clj

Fix garland word tests

---

src/battle_asserts/issues/supremum_syracuse.clj

Added description to sequence and division by 2 for odd numbers

Update supremum_syracuse.clj (closed #1064)

---

src/battle_asserts/issues/partiphify.clj

Fix partiphify solution

---

src/battle_asserts/issues/subnet_checker.clj

В продолжение Issue https://github.com/hexlet-codebattle/battle_asserts/issues/1070
Внесенные изменения:
1. откоорректировано описание задачи на русском и английском языке
2. откорректированы тест-кейсы:
2.1.  изменен порядок следования аргументов
2.2. в 1 и 2 тест-кейсах изменен адрес сети

#1070 Subnet checker
